baseURL = "https://herdgame.netlify.app/"
languageCode = "en-us"
title = "Herd Website"
theme = "gallery"

[params]
  description = "Herd Website"
  author = "Pierre Aceituno"
  defaultTheme = "dark"

